version: "3.4"
services:
  garie-webscore:
    build: .
    privileged: true
    ports:
      - 3000:3000
    environment:
      - INFLUX_TOKEN=dev-token
      - INFLUX_ORG=garie
      - PAGE_USERNAME=admin
      - PAGE_PASSWORD=admin
      - TEST_SUBSCRIPTION_EVENTS=false
    depends_on:
      - postfix
      - influxdb
  influxdb:
    image: "influxdb:2.7"
    volumes:
      - /var/lib/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
      - DOCKER_INFLUXDB_INIT_ORG=garie
      - DOCKER_INFLUXDB_INIT_BUCKET=default
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=dev-token
  postfix:
    image: eeacms/postfix:latest
    environment:
      MTP_HOST: "eea.europa.eu"
      MTP_RELAY: "ironports.eionet.europa.eu"
      MTP_PORT: "8587"
